site_name: LeeMakelog
site_url: https://pashiran.github.io/
repo_url: https://github.com/pashiran/LeeMakelog.github.io
repo_name: LeeMakelog.github.io
site_dir: site
docs_dir: docs

nav:
  - Home: index.md
  - Projects:
      - Meshtastic Hangul: projects/meshtastic-hangul/index.md
      - Universal I2C Keyboard: projects/universal-i2c-keyboard/index.md
      - Everyday Calendar: projects/everyday-calendar/index.md
      - Poetry Camera: projects/poetry-camera/index.md
      - Robotics: projects/robotics/index.md
  - Articles:
      - Electronics: articles/electronics/index.md
      - 3D Printing: articles/3d-printing/index.md
      - CAD: articles/cad/index.md
      - Firmware: articles/firmware/index.md
  - About: about/index.md

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - content.code.copy
    - content.action.edit
    - toc.follow
    - announce.dismiss
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        ko:
          name: 한국어
          build: true
      nav_translations:
        ko:
          Home: 홈
          Projects: 프로젝트
          Meshtastic Hangul: 메스타스틱 한글화
          Universal I2C Keyboard: 범용 I2C 키보드
          Everyday Calendar: 에브리데이 캘린더
          Poetry Camera: 포에트리 카메라
          Robotics: 로보틱스
          Articles: 아티클
          Electronics: 전자 공학
          3D Printing: 3D 프린팅
          CAD: CAD
          Firmware: 펌웨어
          About: 소개

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 한국어
      link: /ko/
      lang: ko
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pashiran
      name: pashiran on GitHub

watch:
  - docs
